name: "🐛 Bug Report"
description: "Report a bug or unexpected behavior"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report Guide
        A good bug report should be detailed enough for others to reproduce the issue. Please provide all necessary information to understand and replicate the bug. Your effort in reporting is valuable and appreciated!
  - type: input
    id: environment
    attributes:
      label: "🌐 Environment"
      description: "Specify where the bug occurred, such as browser version, operating system, or device."
      placeholder: "e.g., Chrome 100 on Windows 10, iPhone 12 with iOS 14.4, etc."
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: "🔍 Bug Description"
      description: "Provide a clear and concise description of what the bug is."
      placeholder: "The user interface does not respond when I click the submit button..."
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "👣 Steps to Reproduce"
      description: "List the steps to reproduce the behavior you're reporting. Be as specific as possible."
      placeholder: "1. Go to '...',\n2. Click on '....',\n3. Scroll down to '....',\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "🤔 Expected Behavior"
      description: "Explain what you expected to happen when the bug occurred."
      placeholder: "The system should process the data and redirect to the success page..."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "📸 Screenshots/Logs"
      description: "If applicable, add screenshots or error logs to help explain your problem. You can drag and drop images directly into the text area."
      placeholder: "Attach images or paste logs here..."
    validations:
      required: false
  - type: checkboxes
    id: terms-bug
    attributes:
      label: "📜 Bug Reporting Conduct"
      description: By reporting this bug, you confirm adherence to the project's [Code of Conduct](https://github.com/joshcho96/issue_template/blob/main/CODE_OF_CONDUCT.md). Please read it carefully.
      options:
        - label: "I acknowledge that I have read and agree to follow this project's [Code of Conduct](https://github.com/joshcho96/issue_template/blob/main/CODE_OF_CONDUCT.md)"
          required: true
