name: "🚀 Add New Feature"
description: "a new feature for the project"
title: "[Feat]: "
labels: ["feature"]
projects: ["joshcho96/test_project"]
assignees:
  - joshcho91
body:
  - type: markdown
    attributes:
      value: You must take time to fill out this report!
  - type: input
    id: figma
    attributes:
      label: Design File
      description: If there's a design for this feature, please provide the link here
      placeholder: ex. https://www.figma.com/file/...
    validations:
      required: false
  - type: textarea
    id: feature-details
    attributes:
      label: Details
      description: Please provide details for the feature. What does it do? How should it work?
      placeholder: ex. This feature allows users to...
    validations:
      required: true
  - type: textarea
    id: feature-requirements
    attributes:
      label: Requirements
      description: Please add requirements necessary/important for the project.
      placeholder: ex. Must be able to handle 1000 concurrent users
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/joshcho96/issue_template/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
