name: "🚀 Feature Request"
description: "Suggest a new feature for Liberty Labs project"
title: "[Feature Request]: " # Please summarize the feature in your title
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        # New Feature Proposal for Liberty Labs
        We value your contributions and encourage you to provide a detailed description of the proposed feature. Please complete the following information to help us better evaluate and implement your request.

        ---
  - type: input
    id: figma
    attributes:
      label: "Design Reference (Optional)"
      description: "If available, provide the link to any design reference for this feature (e.g., Figma, Adobe XD)."
      placeholder: "e.g., https://www.figma.com/file/..."
    validations:
      required: false
  - type: textarea
    id: feature-details
    attributes:
      label: "Feature Details"
      description: "Describe the scope and functionality of the proposed feature. Include how it should work and the expected benefits to the Liberty Labs project."
      placeholder: "e.g., This feature will allow users to..."
    validations:
      required: true
  - type: textarea
    id: feature-requirements
    attributes:
      label: "Requirements"
      description: "Detail any specific requirements or dependencies for the implementation of this feature. Consider scalability, security, and compatibility."
      placeholder: "e.g., Must support scalability for up to 10,000 users, adhere to industry-standard encryption, etc."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Code of Conduct"
  - type: checkboxes
    id: terms
    attributes:
      label: ""
      description: "As part of our commitment to a positive and professional environment, we require all contributors to adhere to our Code of Conduct."
      options:
        - label: "I have read and agree to abide by the Liberty Labs Code of Conduct."
          required: true
