name: "🚀 Add New Feature"
description: "Propose a new feature for the project"
title: "[Feat]: " # Suggest completing the title with a concise feature synopsis
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤝 Thank you for your contribution!
        🚨 Please take the time to fill out this report with the necessary details. A well-structured feature request helps us better understand your proposal and expedite the review process.

        Please format any code, commands, or links using Markdown code blocks or backticks for clarity.

        ---
  - type: input
    id: figma
    attributes:
      label: "🎨 Design File"
      description: "If there's a design for this feature, please format the Figma link as a code snippet (using backticks) for readability."
      placeholder: "`https://www.figma.com/file/...`"
    validations:
      required: false
  - type: textarea
    id: feature-details
    attributes:
      label: "✨ Feature Details"
      description: "What's the purpose of this feature? Describe what it does, how it should function, and its value to the project."
      placeholder: "This feature allows users to..."
    validations:
      required: true
  - type: textarea
    id: feature-requirements
    attributes:
      label: "📋 Requirements"
      description: "Outline any requirements or constraints that are critical for this feature. Include technical, performance, and user experience considerations."
      placeholder: "Must be able to handle 1000 concurrent users, ensure GDPR compliance, etc."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "📜 Code of Conduct"
      description: "Please acknowledge our Code of Conduct before submitting this issue. This helps maintain a positive and inclusive environment for all contributors."
      options:
        - label: "I agree to follow this project's Code of Conduct."
          required: true
