name: "🚀 Add New Feature"
description: "Propose a new feature for the project"
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## 📢 Feature Request Guide
        Please take the time to fill out this feature request thoroughly. Your detailed input will help us understand your vision and requirements. Let's create something amazing together!
  - type: input
    id: figma
    attributes:
      label: "🎨 Design File"
      description: If there's a design file available for this feature, please provide a link here.
      placeholder: "e.g., https://www.figma.com/file/..."
    validations:
      required: false
  - type: textarea
    id: feature-details
    attributes:
      label: "✏️ Feature Details"
      description: "Provide in-depth details of the feature: its purpose, functionality, and how it adds value."
      placeholder: "This feature allows users to..."
    validations:
      required: true
  - type: textarea
    id: feature-requirements
    attributes:
      label: "📋 Requirements"
      description: List any requirements or dependencies that are essential for the implementation of this feature.
      placeholder: "Must be scalable to handle 1000+ concurrent users, compatible with all modern browsers, etc."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "📜 Code of Conduct"
      description: By submitting this issue, you confirm adherence to the project's [Code of Conduct](https://github.com/joshcho96/issue_template/blob/main/CODE_OF_CONDUCT.md). Please read it carefully.
      options:
        - label: "I agree to follow this project's [Code of Conduct](https://github.com/joshcho96/issue_template/blob/main/CODE_OF_CONDUCT.md)"
          required: true
